#SHORTLISTED COLUMNS

tables <- c(
  "airbreathingref",
  "alieninvasive",
  "diet",
  "diet_items",
  "ecology",
  "ecosystem",
  "eggdev",
  "eggnurserysystem",
  "eggs",
  "estimate",
  "estimatedepth",
  "fecundity",
  "food",
  "foodecosystemtype",
  "fooditems",
  "foodtroph",
  "gillarea",
  "larvae",
  "matrix",
  "maturity",
  "morphdat",
  "morphmet",
  "morphmettlratios",
  "myersdata",
  "pop_r",
  "popchar",
  "popgrowth",
  "poplf",
  "popll",
  "poplw",
  "popqb",
  "predatorecosystemtype",
  "predats",
  "ration",
  "reproduc",
  "sounds",
  "spawnagg",
  "spawning",
  "species",
  "speed",
  "stocks",
  "strains",
  "swimming"
)

# Standardized FishBase ID column names
SPEC_CODE <- "spec_code"
STOCK_CODE <- "stock_code"

TABLES_TO_AVERAGE <- c(
  "redsea_fooditems",
  "redsea_morphmet",
  "redsea_morphmettlratios",
  "redsea_popchar",
  "redsea_popgrowth",
  "redsea_popll",
  "redsea_poplw",
  "redsea_maturity"
)

TABLES_TO_MERGE <- c(
  "redsea_estimate",
  "redsea_fooditems",
  "redsea_matrix",
  "redsea_maturity",
  "redsea_morphdat",
  "redsea_morphmet",
  "redsea_morphmettlratios",
  "redsea_popchar",
  "redsea_popll",
  "redsea_poplw",
  "redsea_species",
  "redsea_stocks"
)

THRESHOLD <- 25

META_COLUMNS_TO_REMOVE <- c(
  "E_CODE",
  "autoctr",
  "EcosystemRefno",
  "Remarks",
  "Entered",
  "Dateentered",
  "Modified",
  "Datemodified",
  "LastModified_estimate",
  "ID_matrix",
  "FamCode_matrix",
  "Linf_comment_matrix",
  "autoctr_morphdat",
  "stock_code_matrix",
  "stock_code_morphdat",
  "Entered_morphdat",
  "DateEntered_morphdat",
  "DateModified_morphdat",
  "autoctr_morphmet",
  "PicName_morphmet",
  "Species_species",
  "Author_species",
  "PicPreferredName_species",
  "FamCode_species",
  "GenCode_species",
  "GoogleImage_species",
  "Entered_species",
  "DateEntered_species",
  "Modified_species",
  "DateModified_species",
  "stock_code_stocks",
  "SynOC_stocks",
  "Level_stocks",
  "IUCN_Code_stocks",
  "IUCN_DateAssessed_stocks",
  "Entered_stocks",
  "DateEntered_stocks",
  "Modified_stocks",
  "DateModified_stocks",
  "Reproductive_guild_matrix"
)

# Values to treat as missing
MISSING_VALUES <- c("", "unknown", "NA")

selected_traits <- c(
  "spec_code",
  "Species",
  "stock_code",
  "MaxLengthTL_estimate",
  "Troph_estimate",
  "seTroph_estimate",
  "a_estimate",
  "sd_log10a_estimate",
  "b_estimate",
  "sd_b_estimate",
  "K_estimate",
  "ComDepthMin_estimate",
  "ComDepthMax_estimate",
  "DepthMin_estimate",
  "DepthMax_estimate",
  "PredPreyRatioMin_estimate",
  "PredPreyRatioMax_estimate",
  "TempPrefMin_estimate",
  "TempPrefMean_estimate",
  "TempPrefMax_estimate",
  "FeedingPath_estimate",
  "MaxLengthSL_estimate",
  "to_matrix",
  "mean_temp_matrix",
  "Life_span_matrix",
  "Generation_time_matrix",
  "tm_matrix",
  "E_matrix",
  "Resilience_matrix",
  "QB_matrix",
  "BodyShapeI_morphdat",
  "OperculumPresent_morphdat",
  "LLinterrupted_morphdat",
  "Notched_morphdat",
  "DorsalSoftRaysMin_morphdat",
  "DorsalSoftRaysMax_morphdat",
  "Genus_species",
  "FBname_species",
  "Fresh_species",
  "Brack_species",
  "Saltwater_species",
  "DemersPelag_species",
  "AirBreathing_species",
  "Vulnerability_species",
  "PriceCateg_species",
  "Dangerous_species",
  "Electrogenic_species",
  "PD50_species"
)


y <- c(
  "MaxLengthTL_estimate",
  "Troph_estimate",
  "seTroph_estimate",
  "mean_temp_matrix",
  "E_matrix",
  "Resilience_matrix",
  "Genus_species",
  "Fresh_species",
  "Brack_species",
  "Saltwater_species",
  "DemersPelag_species",
  "Vulnerability_species",
  "PD50_species",
  "MaxLengthSL_estimate"
)

x <- c(
  "a_estimate",
  "sd_log10a_estimate",
  "b_estimate",
  "sd_b_estimate",
  "K_estimate",
  "ComDepthMin_estimate",
  "ComDepthMax_estimate",
  "DepthMin_estimate",
  "DepthMax_estimate",
  "PredPreyRatioMin_estimate",
  "PredPreyRatioMax_estimate",
  "TempPrefMin_estimate",
  "TempPrefMean_estimate",
  "TempPrefMax_estimate",
  "FeedingPath_estimate",
  "to_matrix",
  "Life_span_matrix",
  "Generation_time_matrix",
  "tm_matrix",
  "QB_matrix",
  "BodyShapeI_morphdat",
  "OperculumPresent_morphdat",
  "LLinterrupted_morphdat",
  "Notched_morphdat",
  "DorsalSoftRaysMin_morphdat",
  "DorsalSoftRaysMax_morphdat",
  "FBname_species",
  "AirBreathing_species",
  "PriceCateg_species",
  "Dangerous_species",
  "Electrogenic_species"
)